### ISSUE TITLE
Input Field Clear

### ISSUE THREAD

**Issue by systemswiki** [TaQuangKhoi/Napkin-Collect-Android#17]
Love this utility. Many thanks!!!! I do a lot of voice input into the text field though after each one is sent I have to manually clear the field. Might it make sense for the field to be cleared once the text is sent? Or have a little clear button? Thanks again for this... I was dreading the thought of having to buy an iPhone to support my addiction to Napkin!

**Comment by TaQuangKhoi** [comment]
HI @systemswiki , Which the icon of clear button do you like?
