### ISSUE TITLE
Napkin rejecting token when Sending from Napkin-Collect-Android

### ISSUE THREAD

**Issue by PaulBrayford** [TaQuangKhoi/Napkin-Collect-Android#19]
I've tried generating multiple tokens but each time I configure in Napkin-Collect-Android and then add a thought and press send, I see Napkin reporting wrong API tokens rejected

**Comment by TaQuangKhoi** [comment]
Hi @PaulBrayford,
Thanks for your report.
Can you provide me the screenshot of the error?

**Comment by PaulBrayford** [comment]
Attached are capture of the screen from Napkin plus the configuration on the Android device

Today, it seems to be working okay, however. what I send from the app *is* appearing in Napkin inbox.

![Screenshot 2023-01-02 151216](https://user-images.githubusercontent.com/121758136/210249870-b2424ea2-bf76-4bba-85a0-41edf75c9c98.png)
![SmartSelect_20230102_151019_Napkin Collect](https://user-images.githubusercontent.com/121758136/210250010-07e2c342-d6b4-404f-a952-b06abeee5cd7.jpg)
