### ISSUE TITLE
Skipping Inbox

### ISSUE THREAD

**Issue by JohnnyFlashX** [TaQuangKhoi/Napkin-Collect-Android#25]
This is so great, and works with lightning speed., thank you very much for this! i love napkin but a android possibility for short notes is essential. you made my day. Only thing: Notes seem to skip the inbox of my napkin account, is that right? They are in the swarm directly, without going through the review in the inbox?

**Comment by TaQuangKhoi** [comment]
Hi @JohnnyFlashX, Is your issue related to this #23.

If your issue is that one, I will fix them soon.

Do you share text from other app to Napkin Collect?
